version: "3.9"

services:
  redis:
    image: redis/redis-stack:latest
    container_name: ai-poc_redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - "./data:/data"
volumes:
  pgdata:
    driver: local
